### ISSUE TITLE
Compiling on arm failing error: conversion from 'int64_t'

### ISSUE THREAD

**Issue by Hadatko** [foundriesio/aktualizr#55]
Hello, i am trying to build libaktualizr-lite in docker image for arm and i got this error:
![image](https://user-images.githubusercontent.com/13130700/171007511-931d3e97-3c20-4a39-85ae-8c00e43de04b.png)

**Comment by mike-sul** [comment]
@Hadatko This issue should be posted to the upstream project `https://github.com/uptane/aktualizr`

**Comment by Hadatko** [comment]
Hi @mike-sul i think github support moving Issue to other repository across github. Can you move it or should i create new one?

**Comment by mike-sul** [comment]
For some reason github doesn't allow me to transfer the issue out of the `foundries` org.

**Comment by Hadatko** [comment]
Ok i will create new issue in main repo.

**Comment by pattivacek** [comment]
I'm fairly sure this was already fixed upstream. Are you sure you don't just need to bump the aktualizr version here?

If not, yep, definitely a bug in aktualizr, and should be easy to fix.

**Comment by Hadatko** [comment]
Hi thank you for such a quick respond. I will talk back to them.

**Comment by Hadatko** [comment]
@mike-sul Can you double check if you are not missing fix from upstream?

I am using default branch. Should i move to other tag?

**Comment by Hadatko** [comment]
@pattivacek Could you point me to the fix? The function fromBase64 looks on both repositories same.

**Comment by pattivacek** [comment]
Oh no, my memory was wrong. No, it wasn't already fixed.

**Comment by Hadatko** [comment]
@mike-sul Is it fixed and we can close this issue?

**Comment by mike-sul** [comment]
> @mike-sul Is it fixed and we can close this issue?

@Hadatko Yes, the fix was pulled to the fio's aklite/aktualizr last year https://github.com/foundriesio/aktualizr/commit/846edc038adaf69c62b8e714ffd2afe427e6df48.
